// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-bus.proto

package cn.rongcapital.mc2.data.bus.protobuf;

public interface BehaviorMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BehaviorMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenantId = 1;</code>
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenantId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string userId = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
