// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-bus.proto

package cn.rongcapital.mc2.data.bus.protobuf;

public final class DataBusProto {
  private DataBusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BehaviorMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BehaviorMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoidResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016data-bus.proto\"K\n\026BehaviorMessageReque" +
      "st\022\020\n\010tenantId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\017\n\007" +
      "message\030\003 \001(\t\"\036\n\014VoidResponse\022\016\n\006result\030" +
      "\001 \001(\0052A\n\007DataBus\0226\n\014pushBehavior\022\027.Behav" +
      "iorMessageRequest\032\r.VoidResponseB6\n$cn.r" +
      "ongcapital.mc2.data.bus.protobufB\014DataBu" +
      "sProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BehaviorMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BehaviorMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BehaviorMessageRequest_descriptor,
        new java.lang.String[] { "TenantId", "UserId", "Message", });
    internal_static_VoidResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoidResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
