// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-bus.proto

package cn.rongcapital.mc2.data.bus.protobuf;

public interface VoidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
